### ISSUE TITLE
New 🐘 PHP 8.2 + 8.3 implementation

### ISSUE THREAD

**Issue by arnapou** [messagetemplates/messagetemplates.org#17]
Introduction
-----
I recently discovered this specification for event & logging and I found it very nice.

This is for me an awesome example of KISS.

I am a senior PHP developer (+20 years) and I love quality and well designed code.

This "issue"
-----

Because I couldn't find any PHP implementation enough modern, I wanted to create mine.

It costs me 3 days of personal work to create this lib [arnapou/message-templates](https://packagist.org/packages/arnapou/message-templates).

It is 100% test covered (I know ... that means less than the fact that there is more test LoC than the lib itself ...).

You may want to add it at your implementations list.

💙

**Comment by nblumhardt** [comment]
Added! That's awesome - thanks for the heads-up, @arnapou, and good luck with the project! :sunglasses:
