### ISSUE TITLE
Clarify semantics when message template uses same argument multiple times

### ISSUE THREAD

**Issue by StephenCleary** [messagetemplates/messagetemplates.org#2]
Please clarify whether the following is legal or implementation-dependent behavior:

    ("The value {value} is less than {otherValue}; choosing {value}", value, otherValue)

(i.e., both `{value}` parts will use the single `value` parameter).

Or whether the following is recommended:

    ("The value {value} is less than {otherValue}; choosing {value}", value, otherValue, value)

**Comment by Suchiman** [comment]
At least in serilog, both forms are illegal, because property names must be unique in the template string.
I remember having refactored a few of those to use a different wording, that avoided redundancy, although it felt a little bit awkward.

**Comment by nblumhardt** [comment]
Also a spec note needed, possibly under "Capturing Rules"?
