### ISSUE TITLE
Add semantics for @ and $

### ISSUE THREAD

**Issue by StephenCleary** [messagetemplates/messagetemplates.org#3]
Currently the specification calls out `@` and `$` prefixes, but their semantics are not specified.

It would be nice to have at least an indication of how they are *commonly* used, even if the specifics are implementation-dependent.

**Comment by Suchiman** [comment]
In [Serilog](https://github.com/serilog/serilog/wiki#why-serilog), they're defined as follow:
> The `@` operator in front of `SensorInput` instructs Serilog to preserve the structure of the object passed in. If this is omitted, Serilog recognises simple types like strings, numbers, dates and times, dictionaries and enumerables; all other objects are converted into strings using `ToString()`. 'Stringification' can be forced using the `$` operator in place of `@`.

**Comment by nblumhardt** [comment]
:+1: - we should probably insert that passage directly into the spec.
