### ISSUE TITLE
Add some form of "MetaData" to the specs?

### ISSUE THREAD

**Issue by moolicc** [messagetemplates/messagetemplates.org#6]
When issuing a log message, it might be useful to throw data relating to the current context into the mix without including said data in the template.

When using a log viewer you could then see this data in a grid view or something with the rest of the data.

So basically just support properties without the template containing associated holes for said properties.

Since the template is directly used as the string that will get rendered, if you ever need to store data that doesn't necessarily need to be presented in the output of a renderer.

Allow me to show an example to better explain:
```json
{
    "template": "Error occurred processing request for user {user}",
    "user": "just bob",
    "stack":"thestacktrace"
}
```
Where the stack trace is included, but not actually displayed because that would be ugly and possibly difficult to read.
I feel like this is something that is already supported by most implementations. What's not included in the template would probably just be ignored by the renderer I'd imagine.

Maybe this was even an intended feature, but I couldn't find anything on it at messagetemplates.org as of this moment.

But maybe actually support this as a feature mentioned on messagetemplates.org?

**Comment by nblumhardt** [comment]
Howdy! The libraries that currently implement message templates have a few different APIs to cover this requirement; for Serilog it looks like:

```csharp
Log.ForContext("OrderId", 10).Information("Adding product {ProductName}", "jam");
```

Here the event will carry both `OrderId` and `ProductName`, but only the latter appears in the template.

In Microsoft.Extensions.Logging, `BeginScope()` with a `Dictionary<string, object>` argument will achieve a similar effect.

We've discussed doing this through templates a few times in the context of Serilog, but didn't find a solution that improved much on what the kinds of APIs mentioned above can achieve.

HTH!

**Comment by moolicc** [comment]
Interesting, thanks! Is there any particular reason why the messagetemplates.org site doesn't directly mention any of this being common in implemented apis? Just curious, mind you.

**Comment by nblumhardt** [comment]
For now, just getting a good record of the template format has proven to be a substantial undertaking - if we broaden the scope to include common implementation details I think it'll get out of hand pretty quickly :-)

**Comment by moolicc** [comment]
Fair enough. But what about named values though? Instead of just position and indexing, what about supporting named holes as well? Because in my current WIP implementation, I have a `ProcessParentTemplate(string template, object parent)` which uses the object's properties to resolve hole values via the property names.

**Comment by nblumhardt** [comment]
This sounds like an interesting extension, although using it would necessitate an allocation for the 'parent' object if there isn't one already - not always desirable if logging is turned "off". (In general, the implementations are all working pretty hard to avoid APIs that require allocations even when no logging takes place, as it increases the cost for adding lower-level events like `Debug` that are intended to be close to zero-cost in production code.)

**Comment by moolicc** [comment]
That makes sense indeed. I however went on ahead and implemented named values by way of parent objects, and also tuple (string, object). But of course, using named values is totally optional in my implementation.

**Comment by nblumhardt** [comment]
Closing for now, but thanks for the discussion, keep us posted with how the implementation goes! 👍
