### ISSUE TITLE
Add another library onto the list?

### ISSUE THREAD

**Issue by moolicc** [messagetemplates/messagetemplates.org#7]
Hello! My logging library at https://github.com/icecreamburglar/waterlogged is ready for use and fully support messagetemplates. I was wondering if we could get it thrown on the list? Thanks.

**Comment by nblumhardt** [comment]
PR'd #8 :+1: 

Congrats on getting it to this stage! :-)

**Comment by moolicc** [comment]
Thanks, nblumhardt! I actually had it there for a while, but life got in the way before I published it. But now I've come back to it, cleaned the library up, and she should be ready to roll!
Honestly though this project has been a blast to write though!
