### ISSUE TITLE
Examples of non-template APIs

### ISSUE THREAD

**Issue by Paurian** [messagetemplates/messagetemplates.org#9]
Could you please provide examples as to why other logging libraries don't meet the criteria of a Template? I'm interested in why Log4Net was excluded. Is it because it uses a different template syntax in the configuration file or for some other reason? Now that we have string interpolation syntax, doesn't that open the door for more logging packages to qualify as "Template"-based?

E.G. logger.Debug($"{person} logged in at {timestamp}"); // using C# 6 string interpolation syntax

Thanks!
-P

**Comment by nblumhardt** [comment]
Hi! Message templates _capture properties_ - the named properties like `"{This} in some message"` become properties of the log event. In log4net and elsewhere, the placeholders in strings are formatted into the string - no properties are captured, you just end up with the formatted message. HTH!
